//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCampus2017X {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartCampus2017X.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Retrieving personal timeline... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string retrieving {
            get {
                return ResourceManager.GetString("retrieving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fri に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string week_fri {
            get {
                return ResourceManager.GetString("week_fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string week_mon {
            get {
                return ResourceManager.GetString("week_mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string week_sat {
            get {
                return ResourceManager.GetString("week_sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string week_thu {
            get {
                return ResourceManager.GetString("week_thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string week_tue {
            get {
                return ResourceManager.GetString("week_tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string week_wed {
            get {
                return ResourceManager.GetString("week_wed", resourceCulture);
            }
        }
    }
}
